var new_lang = {
lt0: 'Megvenni Tinedol olcsón. Árárk, vélemények. Rendejen Tinedol most!',
lt1: 'Kitervezve <br>nanotechnológiák <br>segítségével',
lt2: 'Engedélyezett Országos <br>Bőrgyógyász Szövetségével',
lt3: 'Megrendelni ingyenes hívást',
lt4: 'FELEJTSEN EL ÖRÖKRE',
lt5: 'LÁBGOMBÁSODÁSRÓL, VISZKETÉS ÉS <br>LÁBREPEDÉSRŐL!',
lt6: 'Megszabadít a lábgomba tüneteitől már az első használat után',
lt7: 'Teljesen megszabadít a lábgombától 1 túra alatt',
lt8: 'Leveszi a viszeketést, hántást és a láb bőr ingerlését',
lt9: 'Eltávolítja a kellemetlen szagot',
lt10: 'Normalizálja az izzadást',
lt11: 'Összenöveszti a sebeket és a repedéseket a lábakon',
lt12: 'AKCIÓ',
lt13: 'A széríó limitált, siessen <span>az akciós rendeléshez</span> ebben a hónapban!<br>',
lt14: 'A széríó limitált, siessen <span>az akciós rendeléshez</span> ebben a hónapban!<br>',
lt15: 'Az akció végéíg maradt:',
lt16: 'Óra',
lt17: 'Perc',
lt18: 'Másodperc',
lt19: 'Átlagos ár:',
lt20: 'Akciós ár ebben a hónapban:',
lt21: 'Rendelés',
lt22: 'Az adatai be vannak védve',
lt23: 'Még mindig azt gondolja hogy veszély zónában van?<br>Probálja ki magát a tünetekre. Ha legalább az egyik tünete megvan, akkor VÁRAKOZÁS NÉLKŰL KEZDJE EL A GYÓGYÚLÁST!!!',
lt24: 'Kellemetlen, kesetű szag',
lt25: 'Égégs és viszketés talp környékén',
lt26: 'Repedések a sarkakon és a lábakon',
lt27: 'Hólyagok és elvörösödések a lábakon',
lt28: 'Rossz köröm forma',
lt29: 'Zsibbadtság és talpban való szúrás',
lt30: 'A köröm színének megváltozása rózsaszínről sárgára(barnára)',
lt31: 'Köröm vastagódása',
lt32: 'Fehér foltok a körmön',
lt33: 'Bemélyedések, és keményedések a talp körnékén',
lt34: 'Mit várjunk ha nem teszünk a lággomba ellen?',
lt35: 'Statisztika szerint, minden 3. lakosa az országunknak legalább egyszer találkozott a láb gombával. És minden 5. ilyen betegséggel rendelkezik. A lábgomba gyorsan fejlődik, ha szoros cipőt visel nem természetes anyagokbol, zokni szintetikai fonalakból, és ha gyakran szaunnázik vagy medencézik. Nyáron a veszélyek mindenhól vannak strandokon, parkokban, mindenhol ahol mezitláb járnak még az ön fürdő kádjában is!',
lt36: 'ÁLLÍTSA MEG A BETEGSÉG TOVÁBBMENETÉT! ÉS VÉDJE MEG AZ EGÉSZSÉGÉT!',
lt37: 'A lábgomba első lépései:',
lt38: '<i></i>Járás kényelmetlenség',
lt39: '<i></i>Kellemetlen illat',
lt40: '<i></i>Nagy izzadás',
lt41: '<i></i>Végtelen viszketés',
lt42: '<i></i>Folyamatos recsegés',
lt43: 'A lábgomba második lépései:',
lt44: '<i></i>Erős viszketés járás közben',
lt45: '<i></i>Kemény bőr',
lt46: '<i></i>Nagy repedések a sarkakon',
lt47: '<i></i>Erős kellemetlen szag',
lt48: '<i></i>Gyenge elsárgúló körmök',
lt49: 'A lábgomba harmadik lépései:',
lt50: '<i></i>Gennyes repedések',
lt51: '<i></i>Köröm veszítés',
lt52: '<i></i>Mély vérző repedések',
lt53: '<i></i>Kellemetlen hang az újjak között',
lt54: '<i></i>Fehér bőrdarabkák',
lt55: 'Ha nem gyógyítja a gombát akkor el lehet indítani egy nehéz betegéseg! Képzelje el hogyan szemved a fájdalomtól, viszketéstől és undorító kinézetétől meg láb szagától. Azt akarja hogy ez mind önnel történjen meg? AKKOR MONDJON NEMET A LÁBGOMBÁNAK!!',
lt56: 'Gombaelleni krém, <span>EZÜST DRABKÁKKAL GAZDAGÍTOTT</span>',
lt57: 'Hogyan műkődik a <span class="title4-span1">Tinedol krém?</span>',
lt58: 'Tinedol gyakori használata megszabadít sok lábbőr problémától. Belejárúló az összetevők segítenek az első használattól örökre meg SZABADÚLNI:',
lt59: 'Lábgomba',
lt60: 'Kellemetlen szag',
lt61: 'Izzadás',
lt62: 'Repedések',
lt63: 'Elkeményedett bőrt',
lt64: 'Viszketés és kényelmetlenség járás közben',
lt65: '<span class="consist__text--b">Klimbazol</span> — megállítja a gomba fejlődését. Megszabadít a viszketéstől. Romboló munkát végez a gombára.',
lt66: '<span class="consist__text--b">Farenzol</span> — “kikapcsolja” az izzadó ereket. Szárítja és kellemes illatott ajándékozz sok időre.',
lt67: '<span class="consist__text--b">Propolisz</span> - erős antibakteriális tulajdonságokkal rendelkezik.',
lt68: '<span class="consist__text--b">Tea Fa Olaja</span> - bejút a bőr réteg alá, kigyógyítva a problémás bőr területeket, hidegséget ajándékozz és eltávolítja a kellemetlen szagot egész munkanapon keresztűl.',
lt71: 'A krém egyszer s örökre eltávolítja a gombát és a kényelmetlen érzésektől a lábakban, amik követik min azokat akik legalább egyszer találkoztak a lábgombával.',
lt72: 'A krém gyorsan beszívódik, nincsen fényes foltja és egyenletesen elosztódik az egész talpon. Nem hagy jeleket. Elég rákenni a krémet mindkét talpra (alsó és felső rész), masszázs mozdulatokkal bekenni a bőrbe és 1-2 percíg tartani, amíg bele nem szívódík a bőrbe.',
lt73: 'Limitált szállítmány!<br>Siessen!<br> Csak <span class="product-how-much"><span class="lastpack"></span> csomag</span><br>külön árón!',
lt74: 'Tinedol - egy egszerű módszer megszabadúlni a gombától ÖRÖKRE!',
lt75: 'Átlagos ár:',
lt76: 'Akciós ár ebben a hónapban:',
lt77: 'Limitált szállítmány!<br>Siessen!<br> Csak <span class="product-how-much"><span class="lastpack"></span> csomag</span><br>külön árón!',
lt78: 'Töltse ki az ábrát',
lt79: 'MI TÖRTÉNIK A TALPÁVAL Tinedol 30 NAP HASZNÁLATA UTÁN',
lt80: 'Ön örökre megszabadúl a gombától a talpán és a körmén',
lt81: 'Önt elhadja a kényelmetlenség és a viszketés a lábakban',
lt82: 'Az ön lába örökre megszabadúl a kellemetlen szagtól',
lt83: 'Komfortot és puhaságot fog érezni járás közben',
lt84: 'A lába nem fog annyira erősen izzadni',
lt85: 'A lábbőr megújúl és puha meg egyenes lesz',
lt86: 'A körme tökéletes állapotba merűl',
lt87: 'Szép lába lesz amit már nem lesz ciki a medencébe rakni',
lt88: 'HOGYAN HELYES A Tinedol KRÉM HASZNÁLATA',
lt89: 'Mossa meg a lábát, törölje szárazra. Kenjen rá vékony krém réteget fent meg lent is. Kenje be a bőrébe, és várja meg amíg felszívja (1-2 perc). Ismételje minden este alvás előtt 30-35 napon keresztűl. És már a túra végére <strong>meglátja hoyg hogyan változik a bőre, és a körme EGÉSZSÉGES LESZ!</strong>',
lt90: 'Limitált szállítmány!<br>Siessen!<br> Csak <span class="product-how-much"><span class="lastpack"></span> csomag</span><br>külön árón!',
lt91: 'Miért a Tinedol krém hatásosabb mint a többi gomba elleni szer?',
lt92: 'Gombaelleni szerek két kategóriára bontódnak: vagy nem műkődnek, vagy addig segítenek amíg használják őket. Ha gombával találkozott, akkor biztos tudja hogy miről avn szó, és mindig nem műkődő krémeket használ.',
lt93: '<strong>Tinedol</strong> teljsen megváltoztatja a gombaelleni szerekről való véleményt. Nagy klínikai kisérletek megmutatják hogy ez a krém nagyon hatásoson megöli a talp és a köröm gombát. Az első használati kúra után a gomba eltűnik örökre. Ez a hatás jó összetevők miatt van.',
lt94: 'Szakértő véleménye - dermatológus',
lt95: 'A krém teljes vizsgálatai után <strong>Tinedol</strong> én biztosra tudom mondani, hogy ez egy nagyon hatásos szer. És ami a lényeg ebben a krémben - komplexes talpbőr vigyázás. Még ha már az egyik tünete megvan, akkor önnek <strong>már javasolt</strong> a krém használata <strong>Tinedol</strong>, hogy kikerülje a veszélyes betegségeket. Emlékezzen, a talp gomba gyorsan jelenik meg és nagyon gyorsan terjeszkedik! Ma kis kénylmetlenséget és rövíd viszketést érez holnap meg már antibiotikomot vog inni. NE HÚZZON A GYÓGYULÁSSAL! Végezzen a problémával már az első tüneteknél. És tudja! Lábgomba - leges leg terjeszekedőbb betegség. Már elég hozzáérni a probléma kezdetéhez és már van esély a megbetegedésre, vagyis még az egész családra is!',
lt96: '— Németh Sándor<br>k.m.n., MMCN N. Nagy. Dermatologus orvos, kozmetológus, mikológus.',
lt97: 'Visszajelzések',
lt98: 'Én mindig azt hittem hogy a lábgomba engem sose fog érínteni. De amikor a medencézés után el kezdett viszketni a lábam, én rájöttem hogy végűl is megbetegettem… Ami előtt használtam Tinedol én sok szert kipróbáltam, amik egy időre eltűntetik a viszketést és a repedéseket. De ez mind csak pár napra segített. Végűl, amikor a sarkam megrepedt és elkezdett vérezni, orvoshoz mentem. És ő ajánlotta nekem Tinedol. És mostmár nem félek levenni a cipőt a strandon!<br>Köszönöm!',
lt99: 'Mária, Székesfehérvár',
lt100: 'Amikor megrepedeztek a sarkaim, emlékeztem, hogy a mamámnak meg a papámnak is ilyennye van. De ők már majdnem 70 évesek én meg csak 28! Ez borzalmas volt. Utána megértettem hogy ez még is csak a lábgomba, főleg akkor amikor a repedések nagyon erősen viszketni kezdtek. Utána meg emlékeztem hogy egy hónapon keresztűl medencébe jártam papucs nékűl, és rájöttem honnan van a gomba. Végűl megtuttam hogy a barátnőmnek segített a Tinedol, kipróbáltamm mindent! Megint fiatalak a talpaim!!!',
lt101: 'Barbara, Balatonfüred',
lt102: 'Már sok ideje probálom kigyógyítani a lábgombát harapással, amíg nem égettem el vele a bőrőm... Ez nagyon fájdalmas volt és kellemetlen. A lábgomba az nekem gyakori probléma, azért mert a láb izzadás nálam nagyon fejlett. Anyukámnál megtuttam a Tinedol -ről, kiprobáltam, megszabadúltam a gombátol meg a viszketéstől!',
lt103: 'Kata, Kiskunység',
lt104: 'Postával szállítás',
lt105: 'vagy szállítóval',
lt106: 'Konfidiciál garantált.',
lt107: 'Utánfizets.',
lt108: 'Hogyan dolgozunk:',
lt109: 'Ön meghadja a jelentkezést',
lt110: 'az oldalon',
lt111: 'Mi pedig kapcsolatba állunk',
lt112: 'Önnel',
lt113: 'Küldjük az ön',
lt114: 'Csomagát',
lt115: 'Fizetés az után ami után',
lt116: 'megkapja',
lt117: 'Operátorjaink online',
lt118: 'Mindig hétvége nélkűl - rendeljen!',
};

function Translater () {
 for (class_name in new_lang) {
  var elements = document.getElementsByClassName(class_name);
  if (elements.length) {
   for (key in elements) {
    elements[key].innerHTML = new_lang[class_name];
   }
  }
 }
};